/* Pursuit Iron 4.0 — M234 production release. */
const CACHE="pursuit-iron-production-v4-0-0-m234-candidate-selection-b831-rd23581c826573cc8";
const PURSUIT_CACHE=/^pursuit-iron-(?:next-(?:beta|only|lab)|production)-/;
const SHELL=[
  "./app.css",
  "./favicon.ico",
  "./gallery.json",
  "./icons/icon-192-aa9e4b77f520.png",
  "./icons/icon-512-5bdeae240e55.png",
  "./icons/icon-maskable-512-1d7393c9a2de.png",
  "./index.html",
  "./manifest.webmanifest",
  "./modules/App.js",
  "./modules/engine-api.js",
  "./modules/engine-shell.js",
  "./modules/generation-runtime.js",
  "./modules/generation-worker.js",
  "./modules/legacy-research-data.js",
  "./modules/main.js",
  "./modules/mobile-lifecycle.js",
  "./modules/next-engine/allocator.js",
  "./modules/next-engine/app-shell-adapter.js",
  "./modules/next-engine/arbiter.js",
  "./modules/next-engine/arm-coverage.js",
  "./modules/next-engine/athlete-response.js",
  "./modules/next-engine/candidate-optimization.js",
  "./modules/next-engine/capacity-generation.js",
  "./modules/next-engine/capacity-policy.js",
  "./modules/next-engine/coach-regression.js",
  "./modules/next-engine/config.js",
  "./modules/next-engine/cycle-runtime-adapter.js",
  "./modules/next-engine/cycles.js",
  "./modules/next-engine/domain-contracts.js",
  "./modules/next-engine/dose-reconciliation.js",
  "./modules/next-engine/engine-context.js",
  "./modules/next-engine/events.js",
  "./modules/next-engine/exercise-db.js",
  "./modules/next-engine/exercise-economy.js",
  "./modules/next-engine/exercise-selection-intelligence.js",
  "./modules/next-engine/explainability.js",
  "./modules/next-engine/extended-exercise-catalog.js",
  "./modules/next-engine/focus-intent.js",
  "./modules/next-engine/functional-coverage-repair.js",
  "./modules/next-engine/functional-coverage.js",
  "./modules/next-engine/generate.js",
  "./modules/next-engine/generation-recovery.js",
  "./modules/next-engine/history-contract.js",
  "./modules/next-engine/history.js",
  "./modules/next-engine/ledgers.js",
  "./modules/next-engine/live-autoregulation.js",
  "./modules/next-engine/loading.js",
  "./modules/next-engine/method-policy.js",
  "./modules/next-engine/percentage-protocols.js",
  "./modules/next-engine/performance.js",
  "./modules/next-engine/phase-policy.js",
  "./modules/next-engine/phase-transition.js",
  "./modules/next-engine/prescription.js",
  "./modules/next-engine/progression-style.js",
  "./modules/next-engine/public-mev.js",
  "./modules/next-engine/realizer-arm-repair.js",
  "./modules/next-engine/realizer-capacity-repair.js",
  "./modules/next-engine/realizer-dose-ledger.js",
  "./modules/next-engine/realizer-dose-repair.js",
  "./modules/next-engine/realizer-fragment-repair.js",
  "./modules/next-engine/realizer-hypertrophy.js",
  "./modules/next-engine/realizer-math.js",
  "./modules/next-engine/realizer-pairing.js",
  "./modules/next-engine/realizer-prescriptions.js",
  "./modules/next-engine/realizer-public-dose-repair.js",
  "./modules/next-engine/realizer-ranking.js",
  "./modules/next-engine/realizer-sequence.js",
  "./modules/next-engine/realizer-session-builder.js",
  "./modules/next-engine/realizer-strength.js",
  "./modules/next-engine/realizer-structure-repair.js",
  "./modules/next-engine/realizer-time-budget.js",
  "./modules/next-engine/realizer.js",
  "./modules/next-engine/recovery-realization.js",
  "./modules/next-engine/recovery.js",
  "./modules/next-engine/response.js",
  "./modules/next-engine/semantic-exercise-graph.js",
  "./modules/next-engine/setup-economy.js",
  "./modules/next-engine/shell-equipment.js",
  "./modules/next-engine/shell-projection.js",
  "./modules/next-engine/simulation.js",
  "./modules/next-engine/techniques.js",
  "./modules/next-engine/topology.js",
  "./modules/next-engine/volume-repair.js",
  "./modules/next-engine/weekly-recovery.js",
  "./modules/next-engine/workout-history-adapter.js",
  "./modules/next-engine/workout-runtime.js",
  "./modules/program-duration.js",
  "./modules/training-domain.js",
  "./modules/training-domain/analytics.js",
  "./modules/training-domain/catalog.js",
  "./modules/training-domain/prescriptions.js",
  "./modules/training-domain/programs.js",
  "./modules/training-domain/records.js",
  "./modules/ui-motion.js",
  "./modules/wizard-stability.js",
  "./vendor/lucide-react.js",
  "./vendor/react-dom-client.js",
  "./vendor/react-dom.js",
  "./vendor/react-jsx-runtime.js",
  "./vendor/react-shared-JU7Z5GYC.js",
  "./vendor/react-shared-V673FGIV.js",
  "./vendor/react.js"
];
const RESCUE_CACHE='pursuit-iron-production-m100';
self.addEventListener('install',e=>{e.waitUntil((async()=>{const c=await caches.open(CACHE);await c.addAll(SHELL.map(u=>new Request(u,{cache:'reload'})));const keys=await caches.keys();if(keys.includes(RESCUE_CACHE))await self.skipWaiting();})());});
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE&&(PURSUIT_CACHE.test(k)||/^wpb-shell-/.test(k))).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;
// Android checks this stable manifest URL independently of our in-app update prompt.
// Always offer the current network manifest, while retaining the certified offline copy.
const manifestUrl=new URL('./manifest.webmanifest',self.registration.scope);
const requestUrl=new URL(r.url);
if(requestUrl.origin===manifestUrl.origin&&requestUrl.pathname===manifestUrl.pathname){
  e.respondWith((async()=>{const c=await caches.open(CACHE);try{const res=await fetch(new Request(r,{cache:'no-cache'}));if(res.ok){await c.put(manifestUrl.href,res.clone()).catch(()=>{});return res;}}catch{}const saved=await c.match(manifestUrl.href);return saved||new Response('Manifest unavailable',{status:503});})());return;
}
if(r.mode==='navigate'){e.respondWith(caches.open(CACHE).then(c=>c.match('./index.html')).then(x=>x||fetch(r)).catch(()=>caches.open(CACHE).then(c=>c.match('./index.html'))));return;}e.respondWith(caches.open(CACHE).then(c=>c.match(r,{ignoreSearch:true}).then(x=>x||fetch(r).then(res=>{if(res&&res.status===200&&res.type==='basic')c.put(r,res.clone()).catch(()=>{});return res;}))));});
