import { EXTENDED_EXERCISE_CATALOG } from './extended-exercise-catalog.js';
const f = (systemic, axial, lowerBack, grip, shoulder, elbow, knee) => ({ systemic, axial, lowerBack, grip, shoulder, elbow, knee });
export const CURATED_EXERCISES = [
    { id: 'barbell_bench', name: 'Barbell Bench Press', equipment: ['barbell', 'bench', 'rack'], movementFamily: 'horizontal_press', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { chest: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, front_delts: { role: 'secondary', credit: .5 } }, fatigue: f(3, 1, 0, 1, 3, 2, 0), stability: 4, loadability: 7, technicalComplexity: 5, setupCost: 4, practicalReps: [1, 15], preferredReps: { strength: [3, 6], hypertrophy: [5, 12] }, suitability: { hypertrophy: 6, strength: 7 }, liftSpecificity: { bench_press: 1 } },
    { id: 'paused_bench', name: 'Paused Bench Press', equipment: ['barbell', 'bench', 'rack'], movementFamily: 'horizontal_press', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { chest: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, front_delts: { role: 'secondary', credit: .5 } }, fatigue: f(3, 1, 0, 1, 3, 2, 0), stability: 4, loadability: 6, technicalComplexity: 5, setupCost: 4, practicalReps: [2, 12], preferredReps: { strength: [3, 7], hypertrophy: [5, 10] }, suitability: { hypertrophy: 6, strength: 7 }, liftSpecificity: { bench_press: .95 } },
    { id: 'incline_smith', name: 'Incline Smith Press', equipment: ['smith', 'bench'], movementFamily: 'horizontal_press', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { chest: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, front_delts: { role: 'secondary', credit: .5 } }, fatigue: f(2, 0, 0, 0, 2, 1, 0), stability: 7, loadability: 6, technicalComplexity: 2, setupCost: 2, practicalReps: [5, 20], preferredReps: { hypertrophy: [8, 12] }, suitability: { hypertrophy: 7, strength: 3 }, liftSpecificity: { bench_press: .55 } },
    { id: 'machine_press', name: 'Machine Chest Press', equipment: ['machine'], movementFamily: 'horizontal_press', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { chest: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, front_delts: { role: 'secondary', credit: .5 } }, fatigue: f(2, 0, 0, 0, 2, 1, 0), stability: 7, loadability: 6, technicalComplexity: 1, setupCost: 1, practicalReps: [5, 25], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 7, strength: 2 }, liftSpecificity: { bench_press: .3 } },
    { id: 'cable_fly', name: 'Cable Fly', equipment: ['cable'], movementFamily: 'chest_adduction', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { chest: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 1, 0, 0), stability: 6, loadability: 3, technicalComplexity: 2, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [12, 20] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'chest_supported_row', name: 'Chest-Supported Row', equipment: ['dumbbell', 'bench'], equipmentAlternatives: [['machine']], movementFamily: 'horizontal_pull', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { back: { role: 'primary', credit: 1 }, biceps: { role: 'secondary', credit: .5 }, rear_delts: { role: 'secondary', credit: .5 } }, fatigue: f(2, 0, 0, 2, 0, 1, 0), stability: 7, loadability: 6, technicalComplexity: 2, setupCost: 2, practicalReps: [5, 20], preferredReps: { hypertrophy: [6, 12], strength: [5, 10] }, suitability: { hypertrophy: 7, strength: 5 } },
    { id: 'barbell_row', name: 'Barbell Row', equipment: ['barbell'], movementFamily: 'horizontal_pull', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { back: { role: 'primary', credit: 1 }, biceps: { role: 'secondary', credit: .5 }, rear_delts: { role: 'secondary', credit: .5 } }, fatigue: f(4, 4, 5, 3, 0, 1, 0), stability: 3, loadability: 7, technicalComplexity: 5, setupCost: 3, practicalReps: [3, 15], preferredReps: { hypertrophy: [6, 12], strength: [4, 8] }, suitability: { hypertrophy: 5, strength: 6 } },
    { id: 'neutral_pulldown', name: 'Neutral-Grip Pulldown', equipment: ['cable'], equipmentAlternatives: [['machine']], movementFamily: 'vertical_pull', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { back: { role: 'primary', credit: 1 }, biceps: { role: 'secondary', credit: .5 } }, fatigue: f(2, 0, 0, 2, 0, 1, 0), stability: 6, loadability: 6, technicalComplexity: 2, setupCost: 1, practicalReps: [5, 20], preferredReps: { hypertrophy: [8, 12] }, suitability: { hypertrophy: 7, strength: 4 } },
    { id: 'pullup', name: 'Pull-Up', equipment: ['pullup_bar', 'bodyweight'], movementFamily: 'vertical_pull', flags: { barbell: false, bodyweight: true, compound: true }, muscles: { back: { role: 'primary', credit: 1 }, biceps: { role: 'secondary', credit: .5 } }, fatigue: f(3, 0, 0, 3, 0, 1, 0), stability: 4, loadability: 4, technicalComplexity: 4, setupCost: 1, practicalReps: [3, 20], preferredReps: { hypertrophy: [5, 12], strength: [3, 8] }, suitability: { hypertrophy: 6, strength: 5 } },
    { id: 'rear_delt_fly', name: 'Reverse Pec Deck', equipment: ['machine'], movementFamily: 'rear_delt', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { rear_delts: { role: 'primary', credit: 1 }, back: { role: 'minor', credit: .25 } }, fatigue: f(1, 0, 0, 0, 1, 0, 0), stability: 7, loadability: 3, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [12, 20] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'cable_lateral_raise', name: 'Cable Lateral Raise', equipment: ['cable'], movementFamily: 'lateral_raise', flags: { barbell: false, bodyweight: false, compound: false, unilateral: true }, muscles: { side_delts: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 1, 0, 0), stability: 6, loadability: 3, technicalComplexity: 2, setupCost: 1, practicalReps: [8, 35], preferredReps: { hypertrophy: [12, 20] }, suitability: { hypertrophy: 7, strength: 1 } },
    /* Band Lateral Raise now matches the 14 other band movements (stability 4, setup cost 1). At stability 5 / setup 0 it
       outranked the Dumbbell Lateral Raise on every tiebreak and took a side-delt slot in 36 of 65 full-gym programs. */
    { id: 'band_lateral_raise', name: 'Band Lateral Raise', equipment: ['bands'], movementFamily: 'lateral_raise', flags: { barbell: false, bodyweight: false, compound: false, unilateral: true }, muscles: { side_delts: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 1, 0, 0), stability: 4, loadability: 2, technicalComplexity: 2, setupCost: 1, practicalReps: [10, 40], preferredReps: { hypertrophy: [15, 30] }, suitability: { hypertrophy: 6, strength: 1 } },
    { id: 'machine_ohp', name: 'Machine Shoulder Press', equipment: ['machine'], movementFamily: 'vertical_press', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { front_delts: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, side_delts: { role: 'minor', credit: .25 } }, fatigue: f(2, 0, 0, 0, 3, 2, 0), stability: 7, loadability: 5, technicalComplexity: 2, setupCost: 1, practicalReps: [5, 20], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 6, strength: 3 }, liftSpecificity: { overhead_press: .45 } },
    { id: 'preacher_curl', name: 'Preacher Curl', equipment: ['machine'], equipmentAlternatives: [['dumbbell', 'bench']], movementFamily: 'elbow_flexion', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { biceps: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 1, 0, 1, 0), stability: 7, loadability: 4, technicalComplexity: 1, setupCost: 1, practicalReps: [6, 25], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 7, strength: 2 } },
    { id: 'cable_curl', name: 'Cable Curl', equipment: ['cable'], movementFamily: 'elbow_flexion', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { biceps: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 1, 0, 1, 0), stability: 6, loadability: 4, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 15] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'cable_triceps', name: 'Cable Triceps Extension', equipment: ['cable'], movementFamily: 'elbow_extension', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { triceps: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 1, 0), stability: 7, loadability: 4, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 15] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'overhead_cable_triceps', name: 'Overhead Cable Triceps Extension', equipment: ['cable'], movementFamily: 'elbow_extension', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { triceps: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 1, 1, 0), stability: 6, loadability: 4, technicalComplexity: 2, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 15] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'back_squat', name: 'Back Squat', equipment: ['barbell', 'rack'], movementFamily: 'squat', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { quads: { role: 'primary', credit: 1 }, glutes: { role: 'secondary', credit: .5 } }, fatigue: f(5, 5, 4, 1, 0, 0, 4), stability: 3, loadability: 7, technicalComplexity: 6, setupCost: 5, practicalReps: [1, 12], preferredReps: { strength: [3, 6], hypertrophy: [5, 10] }, suitability: { hypertrophy: 5, strength: 7 }, liftSpecificity: { back_squat: 1 } },
    { id: 'hack_squat', name: 'Hack Squat', equipment: ['machine'], movementFamily: 'squat', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { quads: { role: 'primary', credit: 1 }, glutes: { role: 'secondary', credit: .5 } }, fatigue: f(3, 0, 0, 0, 0, 0, 3), stability: 7, loadability: 6, technicalComplexity: 2, setupCost: 2, practicalReps: [5, 20], preferredReps: { hypertrophy: [6, 12] }, suitability: { hypertrophy: 7, strength: 3 }, liftSpecificity: { back_squat: .3 } },
    { id: 'leg_press', name: 'Leg Press', equipment: ['leg_press'], equipmentAlternatives: [['machine']], movementFamily: 'leg_press', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { quads: { role: 'primary', credit: 1 }, glutes: { role: 'secondary', credit: .5 } }, fatigue: f(3, 0, 0, 0, 0, 0, 2), stability: 7, loadability: 7, technicalComplexity: 2, setupCost: 2, practicalReps: [6, 25], preferredReps: { hypertrophy: [10, 15] }, suitability: { hypertrophy: 7, strength: 3 } },
    { id: 'leg_extension', name: 'Leg Extension', equipment: ['machine'], movementFamily: 'knee_extension', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { quads: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 0, 1), stability: 7, loadability: 5, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 20] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'rdl', name: 'Romanian Deadlift', equipment: ['barbell'], movementFamily: 'hip_hinge', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { hamstrings: { role: 'primary', credit: 1 }, glutes: { role: 'secondary', credit: .5 }, back: { role: 'minor', credit: .25 } }, fatigue: f(5, 5, 5, 3, 0, 0, 0), stability: 3, loadability: 7, technicalComplexity: 5, setupCost: 3, practicalReps: [3, 15], preferredReps: { strength: [4, 8], hypertrophy: [6, 10] }, suitability: { hypertrophy: 6, strength: 6 }, liftSpecificity: { deadlift: .55 } },
    { id: 'seated_leg_curl', name: 'Seated Leg Curl', equipment: ['machine'], movementFamily: 'knee_flexion', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { hamstrings: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 0, 1), stability: 7, loadability: 5, technicalComplexity: 1, setupCost: 1, practicalReps: [6, 25], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 7, strength: 2 } },
    { id: 'hip_thrust', name: 'Hip Thrust', equipment: ['barbell', 'bench'], equipmentAlternatives: [['smith', 'bench'], ['machine']], movementFamily: 'hip_extension', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { glutes: { role: 'primary', credit: 1 }, hamstrings: { role: 'minor', credit: .25 } }, fatigue: f(3, 2, 1, 1, 0, 0, 0), stability: 5, loadability: 7, technicalComplexity: 3, setupCost: 4, practicalReps: [5, 20], preferredReps: { hypertrophy: [8, 12] }, suitability: { hypertrophy: 7, strength: 4 } },
    { id: 'standing_calf', name: 'Standing Calf Raise', equipment: ['machine'], movementFamily: 'calf', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { calves: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 0, 1), stability: 7, loadability: 5, technicalComplexity: 1, setupCost: 1, practicalReps: [6, 25], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 7, strength: 1 } },
    { id: 'cable_crunch', name: 'Cable Crunch', equipment: ['cable'], movementFamily: 'core', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { core: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 0, 0), stability: 6, loadability: 4, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 20] }, suitability: { hypertrophy: 6, strength: 1 } },
    { id: 'incline_db_press', name: 'Incline Dumbbell Press', equipment: ['dumbbell', 'bench'], movementFamily: 'horizontal_press', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { chest: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, front_delts: { role: 'secondary', credit: .5 } }, fatigue: f(2, 0, 0, 1, 2, 1, 0), stability: 4, loadability: 5, technicalComplexity: 3, setupCost: 2, practicalReps: [5, 20], preferredReps: { hypertrophy: [8, 12], strength: [5, 8] }, suitability: { hypertrophy: 7, strength: 4 }, liftSpecificity: { bench_press: .5 } },
    { id: 'one_arm_db_row', name: 'One-Arm Dumbbell Row', equipment: ['dumbbell', 'bench'], movementFamily: 'horizontal_pull', flags: { barbell: false, bodyweight: false, compound: true, unilateral: true }, muscles: { back: { role: 'primary', credit: 1 }, biceps: { role: 'secondary', credit: .5 }, rear_delts: { role: 'minor', credit: .25 } }, fatigue: f(2, 1, 2, 2, 0, 1, 0), stability: 5, loadability: 5, technicalComplexity: 3, setupCost: 2, practicalReps: [6, 20], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 6, strength: 4 } },
    { id: 'db_lateral_raise', name: 'Dumbbell Lateral Raise', equipment: ['dumbbell'], movementFamily: 'lateral_raise', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { side_delts: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 1, 1, 0, 0), stability: 4, loadability: 2, technicalComplexity: 2, setupCost: 1, practicalReps: [8, 35], preferredReps: { hypertrophy: [12, 25] }, suitability: { hypertrophy: 6, strength: 1 } },
    { id: 'db_rear_delt_raise', name: 'Dumbbell Rear-Delt Raise', equipment: ['dumbbell'], movementFamily: 'rear_delt', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { rear_delts: { role: 'primary', credit: 1 }, back: { role: 'minor', credit: .25 } }, fatigue: f(1, 0, 1, 1, 1, 0, 0), stability: 4, loadability: 2, technicalComplexity: 2, setupCost: 1, practicalReps: [10, 30], preferredReps: { hypertrophy: [12, 25] }, suitability: { hypertrophy: 6, strength: 1 } },
    { id: 'db_curl', name: 'Dumbbell Curl', equipment: ['dumbbell'], movementFamily: 'elbow_flexion', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { biceps: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 1, 0, 1, 0), stability: 5, loadability: 3, technicalComplexity: 1, setupCost: 1, practicalReps: [6, 25], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 6, strength: 2 } },
    { id: 'db_overhead_triceps', name: 'Dumbbell Overhead Triceps Extension', equipment: ['dumbbell'], movementFamily: 'elbow_extension', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { triceps: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 1, 1, 1, 0), stability: 5, loadability: 3, technicalComplexity: 2, setupCost: 1, practicalReps: [8, 25], preferredReps: { hypertrophy: [10, 18] }, suitability: { hypertrophy: 6, strength: 1 } },
    { id: 'db_split_squat', name: 'Dumbbell Split Squat', equipment: ['dumbbell'], movementFamily: 'squat', flags: { barbell: false, bodyweight: false, compound: true, unilateral: true }, muscles: { quads: { role: 'primary', credit: 1 }, glutes: { role: 'secondary', credit: .5 } }, fatigue: f(3, 0, 1, 2, 0, 0, 3), stability: 3, loadability: 4, technicalComplexity: 3, setupCost: 1, practicalReps: [6, 20], preferredReps: { hypertrophy: [8, 15] }, suitability: { hypertrophy: 6, strength: 3 }, liftSpecificity: { back_squat: .2 } },
    { id: 'db_rdl', name: 'Dumbbell Romanian Deadlift', equipment: ['dumbbell'], movementFamily: 'hip_hinge', flags: { barbell: false, bodyweight: false, compound: true }, muscles: { hamstrings: { role: 'primary', credit: 1 }, glutes: { role: 'secondary', credit: .5 }, back: { role: 'minor', credit: .25 } }, fatigue: f(3, 2, 3, 2, 0, 0, 0), stability: 4, loadability: 5, technicalComplexity: 3, setupCost: 1, practicalReps: [5, 20], preferredReps: { hypertrophy: [8, 12] }, suitability: { hypertrophy: 6, strength: 4 }, liftSpecificity: { deadlift: .35 } },
    { id: 'db_calf_raise', name: 'Dumbbell Calf Raise', equipment: ['dumbbell'], movementFamily: 'calf', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { calves: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 1, 0, 0, 1), stability: 4, loadability: 3, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 20] }, suitability: { hypertrophy: 6, strength: 1 } },
    { id: 'dumbbell_crunch', name: 'Dumbbell Crunch', equipment: ['dumbbell'], movementFamily: 'core', flags: { barbell: false, bodyweight: false, compound: false }, muscles: { core: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 0, 0), stability: 6, loadability: 2, technicalComplexity: 1, setupCost: 1, practicalReps: [8, 30], preferredReps: { hypertrophy: [10, 20] }, suitability: { hypertrophy: 5, strength: 1 } },
    { id: 'bodyweight_crunch', name: 'Bodyweight Crunch', equipment: ['bodyweight'], movementFamily: 'core', flags: { barbell: false, bodyweight: true, compound: false }, muscles: { core: { role: 'primary', credit: 1 } }, fatigue: f(1, 0, 0, 0, 0, 0, 0), stability: 6, loadability: 1, technicalComplexity: 1, setupCost: 0, practicalReps: [10, 40], preferredReps: { hypertrophy: [15, 30] }, suitability: { hypertrophy: 4, strength: 1 } },
    { id: 'conventional_deadlift', name: 'Conventional Deadlift', equipment: ['barbell'], movementFamily: 'hip_hinge', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { hamstrings: { role: 'primary', credit: 1 }, glutes: { role: 'primary', credit: 1 }, back: { role: 'secondary', credit: .5 } }, fatigue: f(7, 7, 7, 5, 0, 1, 1), stability: 2, loadability: 7, technicalComplexity: 7, setupCost: 4, practicalReps: [1, 8], preferredReps: { strength: [2, 5], hypertrophy: [4, 8] }, suitability: { hypertrophy: 3, strength: 7 }, liftSpecificity: { deadlift: 1 } },
    { id: 'barbell_ohp', name: 'Barbell Overhead Press', equipment: ['barbell', 'rack'], movementFamily: 'vertical_press', flags: { barbell: true, bodyweight: false, compound: true }, muscles: { front_delts: { role: 'primary', credit: 1 }, triceps: { role: 'secondary', credit: .5 }, side_delts: { role: 'minor', credit: .25 } }, fatigue: f(4, 2, 1, 1, 4, 2, 0), stability: 3, loadability: 6, technicalComplexity: 5, setupCost: 3, practicalReps: [1, 12], preferredReps: { strength: [3, 6], hypertrophy: [5, 10] }, suitability: { hypertrophy: 5, strength: 7 }, liftSpecificity: { overhead_press: 1 } },
];
// The curated catalog remains the preferred first-party knowledge base. v661's full exercise
// inventory is imported as compatibility breadth, then de-duplicated by stable ID. Curated
// definitions win collisions because they carry newer, intentionally reviewed metadata.
const builtinById = new Map();
const builtinNames = new Set();
const semanticName = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
for (const ex of [...CURATED_EXERCISES, ...EXTENDED_EXERCISE_CATALOG]) {
    const nameKey = semanticName(ex.name);
    if (builtinById.has(ex.id) || builtinNames.has(nameKey))
        continue;
    builtinById.set(ex.id, ex);
    builtinNames.add(nameKey);
}
export const EXERCISES = [...builtinById.values()];
export const EXERCISE_MAP = new Map(EXERCISES.map(e => [e.id, e]));
export function createExerciseCatalog(customExercises = []) {
    const seen = new Set(EXERCISES.map(e => e.id));
    const custom = [];
    for (const ex of customExercises) {
        if (!ex?.id || seen.has(ex.id))
            continue;
        seen.add(ex.id);
        custom.push({ ...ex, source: 'custom', metadataConfidence: ex.metadataConfidence ?? 'low' });
    }
    return [...EXERCISES, ...custom];
}
export function createExerciseMap(customExercises = []) {
    return new Map(createExerciseCatalog(customExercises).map(ex => [ex.id, ex]));
}
export function getExerciseDefinition(id, customExercises = []) {
    if (EXERCISE_MAP.has(id))
        return EXERCISE_MAP.get(id);
    return customExercises.find(ex => ex.id === id);
}
